apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: boots
  name: boots
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: boots
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: boots
    spec:
      containers:
      - args:
        - -dhcp-addr
        - 0.0.0.0:67
        - -tftp-addr
        - :69
        - -http-addr
        - :80
        - -log-level
        - DEBUG
        env:
        - name: API_AUTH_TOKEN
          value: ignored
        - name: API_CONSUMER_TOKEN
          value: ignored
        - name: BOOTP_BIND
          value: :67
        - name: DATA_MODEL_VERSION
          value: "1"
        - name: DNS_SERVERS
          value: 8.8.8.8
        - name: DOCKER_REGISTRY
        - name: ELASTIC_SEARCH_URL
          value: :9200
        - name: FACILITY_CODE
          value: onprem
        - name: HTTP_BIND
          value: :80
        - name: MIRROR_HOST
          value: 127.0.0.1
        - name: PACKET_ENV
          value: testing
        - name: PACKET_VERSION
          value: ignored
        - name: PUBLIC_IP
        - name: REGISTRY_PASSWORD
        - name: REGISTRY_USERNAME
        - name: ROLLBAR_DISABLE
          value: "1"
        - name: ROLLBAR_TOKEN
          value: ignored
        - name: SYSLOG_BIND
          value: :514
        - name: TFTP_BIND
          value: :69
        - name: TINKERBELL_CERT_URL
          value: http://tink-server:42114/cert
        - name: TINKERBELL_GRPC_AUTHORITY
          value: :42113
        image: quay.io/tinkerbell/boots:latest
        imagePullPolicy: Always
        name: boots
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 67
          protocol: UDP
        - containerPort: 69
          protocol: UDP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
